version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/data
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
